In [1]:
import torch
import SoftMaxPool2d
import numpy as np

In [2]:
tsize = (1,32,28,28)
v = torch.arange(int(np.prod(tsize))).float()
t = v.view(tsize)
print(t.shape)

torch.Size([1, 32, 28, 28])


In [3]:
softmaxpool = SoftMaxPool2d.SoftMaxPool2d(1e-2,(2,2),2)
p= softmaxpool(t)

torch.Size([1, 32, 14, 14])
4


In [5]:
tensor_to_numpy = lambda t:t.detach().cpu().numpy()

In [17]:
chnl = 0
softmaxpool.T = torch.tensor(1e-2).float()
p= softmaxpool(t)
print('Input\n\n',
      tensor_to_numpy(t)[0,chnl,:8,:8],
      '\n\n'+'-'*50+'\n\n',
      'Pooled\n\n',
      tensor_to_numpy(p)[0,chnl,:4,:4])

Input

 [[  0.   1.   2.   3.   4.   5.   6.   7.]
 [ 28.  29.  30.  31.  32.  33.  34.  35.]
 [ 56.  57.  58.  59.  60.  61.  62.  63.]
 [ 84.  85.  86.  87.  88.  89.  90.  91.]
 [112. 113. 114. 115. 116. 117. 118. 119.]
 [140. 141. 142. 143. 144. 145. 146. 147.]
 [168. 169. 170. 171. 172. 173. 174. 175.]
 [196. 197. 198. 199. 200. 201. 202. 203.]] 

--------------------------------------------------

 Pooled

 [[ 29.  31.  33.  35.]
 [ 85.  87.  89.  91.]
 [141. 143. 145. 147.]
 [197. 199. 201. 203.]]
